### ISSUE TITLE
Reveal lib outdated

### ISSUE THREAD

**Issue by schniggie** [dtrukr/revealapp_injected#1]
Hey can you please update the dpkg with a new reveal dylib. The current one is outdated.

![os x mavericks - vmware workstation_2015-02-25_15-58-53](https://cloud.githubusercontent.com/assets/637619/6372922/84856360-bd07-11e4-86f4-adc98e5c383f.png)

**Comment by dtrukr** [comment]
I've updated libReveal.dylib to latest version - 1.5.1. The latest binary release is available at https://github.com/dtrukr/revealapp_injected/releases
